#!/bin/bash
# chkconfig: - 85 15
# description: The Apache HTTP Server is an efficient and extensible  \
#	       server implementing the current HTTP standards.
# processname: gwengine 
# config: 
# pidfile: /etc/ddfs/GWEngine.pid

# Source function library.
. /etc/rc.d/init.d/functions

#---------
#HTTPD_LANG=${HTTPD_LANG-"CC"}
OPTIONS=30000

#---------------
GWEngine=${GWEngine-/usr/sbin/NodeClient}
prog=gwclient
pidfile=${PIDFILE-/var/run/NodeClient.pid}
lockfile=${LOCKFILE-/var/run/NodeClient}
RETVAL=0

#---------------- 
start() {
        echo -n $"Starting $prog: "
        #LANG=$HTTPD_LANG daemon --pidfile=${pidfile} $GWEngine $OPTIONS
        daemon --pidfile=${pidfile} $GWEngine $OPTIONS
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}

#--------------------
stop() {
	echo -n $"Stopping $prog: "
	killproc -p ${pidfile} -d 10 $GWEngine
        #kill -9 `lsof -i:$OPTIONS |grep "$OPTIONS"|awk '{print $2}'` 2>/dev/null
        RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
        status -p ${pidfile} $GWEngine
	RETVAL=$?
	;;
  restart)
	stop
	start
	;;
  *)
	echo $"Usage: $prog {start|stop|restart|status}"
	RETVAL=3
esac

exit $RETVAL
