//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MailMgr.cpp
//  @ Date : 2011-8-4
//  @ Author : @gfl
//
//


#include <stdio.h>
#include "GatewayBG/Operation/MailMgr.h"


        const string m_MailCfgFilePath;         //邮件配置文件路径
MailMgr::MailMgr():m_MailCfgFilePath("/etc/scigw/Mail.conf")
{
}

MailMgr::~MailMgr()
{
}

int MailMgr::SetMailInfo(const string& ip, const string& pop3, const string& smtp)
{
        FILE *stream = fopen(m_MailCfgFilePath.c_str(), "w");
        fputs((ip + "\n").c_str(), stream);
        fputs((pop3 + "\n").c_str(), stream);
        fputs((smtp + "\n").c_str(), stream);
        fclose(stream);
        return 0;
}

int MailMgr::GetMailInfo(string& ip, string& pop3, string& smtp)
{       
        char buf[128];

        FILE *stream = fopen(m_MailCfgFilePath.c_str(), "r");
        fgets(buf, 128, stream);
        ip = buf;        
        fgets(buf, 128, stream);
        pop3 = buf;
        fgets(buf, 128, stream);
        smtp = buf;
        fclose(stream);
        return 0;
}

