//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MultiPathMgr.h
//  @ Date : 2011-8-4
//  @ Author : @gfl
//
//


#if !defined(_MULTIPATHMGR_H)
#define _MULTIPATHMGR_H

#include "GatewayBG/Operation/BaseInfo.h"

class MultiPathMgr
{
public:
        int StartMPService();
        int StopMPService();
        int GetServiceStatus(ServiceStatus &status);
};

#endif  //_MULTIPATHMGR_H
