//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : NFSMgr.h
//  @ Date : 2011-8-3
//  @ Author : gfl
//
//


#ifndef _NFSMGR_H
#define _NFSMGR_H

#include <list>
#include <string>
#include "GatewayBG/Operation/BaseInfo.h"
using std::list;
using std::string;

class NFSMgr
{
public:
        NFSMgr();
        ~NFSMgr();
public:
        int StartNFSService();
        int StopNFSService();
        int ClearConfigFile();
        int GetNFSConfig(list<NfsCfgInfo>& nfsCfg);
        int SetNFSConfig(const string& path, const string& ip);
        int GetServiceStatus(ServiceStatus& status);
};

#endif  //_NFSMGR_H
