//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDCacheMgr.h
//  @ Date : 2011-8-4
//  @ Author : @gfl
//
//


#if !defined(_SSDCACHEMGR_H)
#define _SSDCACHEMGR_H

#include <string>
using std::string;

class SSDCacheMgr
{
public:
        SSDCacheMgr();
        ~SSDCacheMgr();
public:
        /**
         * @note: 创建缓存设备，ssd:固态硬盘, sas:数据盘
         */
        int CreateCacheDev(const string& ssd, const string& sas);

        /**
         * @note: 删除缓存设备
         */
        int DestroyCacheDev();

        /**
         * @note: 给缓存设备挂载文件系统
         */
        int MountCacheDev(const string& mp);

        /**
         * @note: 卸载文件系统
         */
        int UnMountCacheDev();

        /**
         * @note: 获取缓存设备信息，包括ssd:固态硬盘, sas:数据盘, cacheDev:缓存设备名, mp:挂载点
         */
        int GetCacheInfo(string& cacheDev, string& ssd, string& sas, string& mp);

private:
        string m_CacheDevPath;
        string m_CacheDevName;
};

#endif  //_SSDCACHEMGR_H
